/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Alert.java
 *
 * Created on 10.08.2010, 22:30:11
 */

package gui;

import java.io.ByteArrayOutputStream;
import java.io.PrintWriter;

/**
 *
 * @author Administrator
 */
public class Alert extends javax.swing.JDialog {

    
	/** Creates new form Alert */
    public Alert() {
        initComponents();
        
        setSize(709, 341);
        setLocationByPlatform( true );
    }
    
    public static void alert( String message ){
    	Alert alert = new Alert();
    	alert.jTextPane2.setText( message );
    	alert.setVisible( true );
    }
    
    public static void alert( Exception e ) {
		ByteArrayOutputStream output = new ByteArrayOutputStream();
		PrintWriter writer = new PrintWriter( output );
		e.printStackTrace( writer );
		writer.flush();
		alert( output.toString() );		
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(jTextPane1);

        setAlwaysOnTop(true);
        setModal(true);

        jScrollPane2.setAutoscrolls(true);

        jTextPane2.setEditable(false);
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

}
